[package]
name = "hipcheck-macros"
description = "Helper macros for the `hipcheck` crate."
repository = "https://github.com/mitre/hipcheck"
version = "0.3.3"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.87"
