[package]
name = "dummy_rand_data"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
hipcheck-sdk = { path = "../../sdk/rust", features = ["macros"] }
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["rt"] }

[dev-dependencies]
hipcheck-sdk = { path = "../../sdk/rust", features = ["macros", "mock_engine"] }
