###############################################################################
# Orgs.toml
#
# This configuration file defines the set of organizations against which
# affiliation may be checked for committers and authors in a repository,
# and how that affiliation determination will be made (the "strategy").
###############################################################################


#==============================================================================
# Strategy
#
# This section defines one of two forms of a strategy, either a single string
# representing the mode (which may be "independent", "affiliated", "all", or
# "none"), or a mode and a list of references (either "country:<country_name>"
# or "org:<org_name>"). Together, these define the list of organizations to be
# considered for matching, and whether to flag identities as concerning if
# if they're _affiliated_ with an org in the list ("affiliated" mode), or are
# _not affiliated_ with an org in the list ("independent" mode).
#==============================================================================

# The strategy spec can be short, implicitly being affiliated with or
# independent from all the orgs in the file.
strategy = "independent"

# The strategy spec would alternatively look like this.
# With this mode, you can more completely specify the orgs or countries
# to include in the list, and mark whether we're rejecting those affiliated
# with or independent from the selected org list.
#
# strategy_spec = { mode = "affiliated", list = ["country:United States", "org:MITRE"] }


#==============================================================================
# Orgs
#
# This section defines a list of organizations, including their name, primary
# affiliated country, and any email hosts known to be connected to them.
#==============================================================================

[[orgs]]
name = "AT&T"
hosts = ["att.com"]
country = "United States"

[[orgs]]
name = "Alibaba"
hosts = ["alibaba.com"]
country = "China"

[[orgs]]
name = "Amazon"
hosts = ["amazon.com"]
country = "United States"

[[orgs]]
name = "Blue Box Cloud"
hosts = ["blueboxcloud.com"]
country = "United States"

[[orgs]]
name = "CERN"
hosts = ["home.cern"]
country = "Switzerland"

[[orgs]]
name = "Cisco"
hosts = ["cisco.com"]
country = "United States"

[[orgs]]
name = "Cloud Foundry"
hosts = ["cloudfoundry.org"]
country = "United States"

[[orgs]]
name = "Code Think"
hosts = ["codethink.co.uk"]
country = "United Kingdom"

[[orgs]]
name = "Comcast"
hosts = ["comcast.com"]
country = "United States"

[[orgs]]
name = "CoreOS"
hosts = ["coreos.com"]
country = "United States"

[[orgs]]
name = "Dell EMC"
hosts = ["dellemc.com", "emc.com"]
country = "United States"

[[orgs]]
name = "DT Dream"
hosts = ["dtdream.com"]
country = "China"

[[orgs]]
name = "Facebook"
hosts = ["facebook.com"]
country = "United States"

[[orgs]]
name = "Fujitsu"
hosts = ["fujitsu.com"]
country = "Japan"

[[orgs]]
name = "Google"
hosts = ["google.com"]
country = "United States"

[[orgs]]
name = "HP"
hosts = ["hp.com", "hpe.com"]
country = "United States"

[[orgs]]
name = "Heroku"
hosts = ["heroku.com"]
country = "United States"

[[orgs]]
name = "Huawei"
hosts = ["huawei.com"]
country = "China"

[[orgs]]
name = "IBM"
hosts = ["ibm.com"]
country = "United States"

[[orgs]]
name = "Influx Data"
hosts = ["influxdata.com"]
country = "United States"

[[orgs]]
name = "Intel"
hosts = ["intel.com"]
country = "United States"

[[orgs]]
name = "MIT"
hosts = ["mit.edu"]
country = "United States"

[[orgs]]
name = "MITRE"
hosts = ["mitre.org"]
country = "United States"

[[orgs]]
name = "Microsoft"
hosts = ["microsoft.com"]
country = "United States"

[[orgs]]
name = "NTT"
hosts = ["ntt.com"]
country = "Japan"

[[orgs]]
name = "Oracle"
hosts = ["oracle.com"]
country = "United States"

[[orgs]]
name = "Orange"
hosts = ["orange.com"]
country = "France"

[[orgs]]
name = "Percona"
hosts = ["persona.com"]
country = "United States"

[[orgs]]
name = "Pivotal"
hosts = ["pivotal.io", "pivotallabs.com"]
country = "United States"

[[orgs]]
name = "Rackspace"
hosts = ["rackspace.com"]
country = "United States"

[[orgs]]
name = "Rakuten"
hosts = ["rakuten.com"]
country = "Japan"

[[orgs]]
name = "Red Hat"
hosts = ["redhat.com"]
country = "United States"

[[orgs]]
name = "RightScale"
hosts = ["rightscale.com"]
country = "United States"

[[orgs]]
name = "SAP"
hosts = ["sap.com"]
country = "Germany"

[[orgs]]
name = "SINA"
hosts = ["sina.com"]
country = "China"

[[orgs]]
name = "SUSE"
hosts = ["suse.com"]
country = "Germany"

[[orgs]]
name = "SalesForce"
hosts = ["salesforce.com"]
country = "United States"

[[orgs]]
name = "Stark & Wayne"
hosts = ["starkandwayne.com"]
country = "United States"

[[orgs]]
name = "Stripe"
hosts = ["stripe.com"]
country = "United States"

[[orgs]]
name = "Swisscom"
hosts = ["swisscom.com"]
country = "Switzerland"

[[orgs]]
name = "Apache"
hosts = ["apache.org"]
country = "United States"

[[orgs]]
name = "ThoughtWorks"
hosts = ["thoughtworks.com"]
country = "United States"

[[orgs]]
name = "Undead Labs"
hosts = ["undeadlabs.com"]
country = "United States"

[[orgs]]
name = "VMWare"
hosts = ["vmware.com"]
country = "United States"

[[orgs]]
name = "Walmart"
hosts = ["walmart.com"]
country = "United States"

[[orgs]]
name = "ZTE"
hosts = ["zte.com.cn"]
country = "China"

[[orgs]]
name = "ZJI"
hosts = ["zji.edu.cn"]
country = "China"

[[orgs]]
name = "NPM"
hosts = ["npmjs.com"]
country = "United States"

[[orgs]]
name = "UK Digital Cabinet Office"
hosts = ["digital.cabinet-office.gov.uk"]
country = "United Kingdom"

[[orgs]]
name = "RBC Royal Bank"
hosts = ["rbcon.com"]
country = "Canada"
