[package]
name = "dummy_sha256"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
hipcheck-sdk = { path = "../../sdk/rust", features = ["macros"]}
sha2 = "0.10.8"
tokio = { version = "1.42.0", features = ["rt"] }
